### ISSUE TITLE
share info from WorldBuffsTracker

### ISSUE THREAD

**Issue by Qeynos** [Pizzahawaiii/PizzaWorldBuffs#14]
I read the WorldBuffsTracker code, and it uses the TWB channel to share information. Is it possible for PizzaWorldBuffs to add an option, defaulting to "false" to receive information from the TWB channel? The priority should be above the red information and below the orange information, maybe yellow font. providing more accurate notifications when there are fewer PizzaWorldBuffs users online.
[WorldBuffsTracker.zip](https://github.com/user-attachments/files/15573973/WorldBuffsTracker.zip)

**Comment by Qeynos** [comment]
The channel name is in line 76, and the logic begins from line 510.

**Comment by Pizzahawaiii** [comment]
I'm assuming the biggest challenge would be parsing all the data PizzaWorldBuffs needs from the TWB messages. I don't have the time to read and understand the whole code right now. Do you have some examples of the message format used by WorldBuffsTracker?

**Comment by Pizzahawaiii** [comment]
As a side note, the way I make sure people always get buff timers on Nordanaar is I leveled two rogues to level 5, put them in Stormwind and Orgrimmar with PizzaWorldBuffs on and wrote a script that makes them jump every 3 minutes so they don't go AFK and log out automatically. Yes I know it's technically botting, but I did talk to TurtleWoW staff and got their permission to do this.

The only real downside is that my PC has to be turned on 24/7 :sweat_smile: Well and sometimes these "buffbots" disconnect and my script has no reconnect logic, which could be fixed if I had more time.

**Comment by Pizzahawaiii** [comment]
> If this method works correctly, then the necessity of integrating WorldBuffsTracker is not high.

Yeah it generally works fine. I just don't want to have 2 characters online on all 6 servers at all times. Doing it 24/7 on one server is already a bit too much for me honestly.

> Today might be an exception because the server was under maintenance, and the bot might not have been able to come online in time. I happened to be online during that period, so the timing information was completely missing. However, I don't know if WorldBuffsTracker had a similar issue.

Which server are you playing on? I checked all 4 or 5 Asian TurtleWoW realms yesterday and in [PizzaWorldBuffs_Monitor](https://github.com/Pizzahawaiii/PizzaWorldBuffs_Monitor) I couldn't see a single person using PizzaWorldBuffs on any of the servers. So looks to me like nobody is using it there yet?

**Comment by Qeynos** [comment]
> > If this method works correctly, then the necessity of integrating WorldBuffsTracker is not high.
> 
> Yeah it generally works fine. I just don't want to have 2 characters online on all 6 servers at all times. Doing it 24/7 on one server is already a bit too much for me honestly.
> 
> > Today might be an exception because the server was under maintenance, and the bot might not have been able to come online in time. I happened to be online during that period, so the timing information was completely missing. However, I don't know if WorldBuffsTracker had a similar issue.
> 
> Which server are you playing on? I checked all 4 or 5 Asian TurtleWoW realms yesterday and in [PizzaWorldBuffs_Monitor](https://github.com/Pizzahawaiii/PizzaWorldBuffs_Monitor) I couldn't see a single person using PizzaWorldBuffs on any of the servers. So looks to me like nobody is using it there yet?

i am on the uk pve server, there are many chinese friends
