### ISSUE TITLE
Pizzaworldbuffs with magehud 

### ISSUE THREAD

**Issue by jendryk** [Pizzahawaiii/PizzaWorldBuffs#16]
With both those addons enabled, pizza doesn’t show any timers and an error shows up. I can upload a screenshot tomorrow if you can’t reproduce

**Comment by Pizzahawaiii** [comment]
Thanks for the report!

Can confirm, here's the error shown when using PizzaWorldBuffs and MageHud together:

![Screenshot from 2024-06-06 22-57-38](https://github.com/Pizzahawaiii/PizzaWorldBuffs/assets/119806513/22f9bbfe-5ded-42ae-a96c-4bf91a084193)

**Comment by Pizzahawaiii** [comment]
@jendryk Fixed in version 1.3.1 (commit [526b43](https://github.com/Pizzahawaiii/PizzaWorldBuffs/commit/526b432cab2ed2a3cad24c0497ea5d0fb97fe1b7)) :tada:
