### ISSUE TITLE
Display 'Auto-Logout Enabled' on the WorldBuff title

### ISSUE THREAD

**Issue by Qeynos** [Pizzahawaiii/PizzaWorldBuffs#2]
Suggest adding a notification in the title indicating that the auto-logout feature is enabled. Additionally, I'm not sure if I missed the correct timing, but when I tried, it did not auto-logout.

**Comment by Qeynos** [comment]
I have found the reason why the trigger did not work. The trigger yell message is limited to English, and it cannot match and trigger in the Chinese client I am using. Are there any plans to add multi-language support? I can assist with the Chinese translation.

**Comment by Qeynos** [comment]
And when used for the first time, an error will be reported because the configuration file has not been generated

**Comment by Pizzahawaiii** [comment]
@Qeynos thanks for the input!

Yeah I thought about adding a permanent "auto-logout enabled" notification somewhere. Thanks for confirming this would actually be a good idea :smile: What do you think about adding it as a separate frame and show it near the center of the screen? Should be safe to assume people will only enable the auto-logout if they go AFK, so a message in the center shouldn't be too disruptive I think.

Also, created separate tickets for the other two issues you mentioned.

**Comment by Pizzahawaiii** [comment]
@Qeynos I added a separate frame for the "Auto-logout/Auto-exit enabled" notification in v1.3.0 (yes, I also added auto-exit: `/wb exit 1` :slightly_smiling_face:)

**Comment by Qeynos** [comment]
great! I'll give it a try and see if there are any better ideas.
