### ISSUE TITLE
Attempt to perform arithmetic on nil value

### ISSUE THREAD

**Issue by Nikki1993** [Pizzahawaiii/PizzaWorldBuffs#26]
Was just walking around Stormwind and got this error message. Can't offer any reproduction steps as it just sort of happened randomly.

![image](https://github.com/user-attachments/assets/ca0f4f20-85ff-43cf-9e6b-13ad687083ab)

**Comment by Pizzahawaiii** [comment]
@Nikki1993 ah yeah I also noticed that. Already pushed a fix, just haven't released it as a new version yet. But if you try downloading the latest GitHub version again, it should be fixed. Please let me know if the error still pops up after you update. Thanks for reporting! :raised_hands:

**Comment by Nikki1993** [comment]
I pulled from master already a while ago when I noticed you pushed potential fix  (I used GitAddonsManager`), hasn't happened yet. Been running back and forth in SW. Not that I know how I got it to pop in the first place :P think it's safe to close this issue for now and re-open later if it happens again.

Thanks!

**Comment by Pizzahawaiii** [comment]
Yup, agreed. Thanks again mate!
