### ISSUE TITLE
Support Mandarin NPC Yell Triggers

### ISSUE THREAD

**Issue by Pizzahawaiii** [Pizzahawaiii/PizzaWorldBuffs#7]
The addon currently only supports the English game client because it only detects the English NPC yell triggers indicating that a buff is about to drop:

```lua
-- These are the NPC yell triggers we use to detect that one of the buffs has dropped.
local yellTriggers = {
  A = {
    O = 'The dread lady, Onyxia, hangs from the arches!',
    N = 'Citizens of the Alliance, the Lord of Blackrock is slain! Nefarian has been subdued',
  },
  H = {
    O = 'The brood mother, Onyxia, has been slain!',
    N = 'NEFARIAN IS SLAIN! People of Orgrimmar, bow down before the might of',
  },
}
```

Should be a fairly easy fix, we just need the exact Mandarin translations of the four NPC yell messages. It doesn't have to be the full yell messages, just a unique part of each of them (like in the code snippet above) should be enough.

See also [this comment](https://github.com/Pizzahawaiii/PizzaWorldBuffs/issues/2#issuecomment-2136458200) in #2.

**Comment by Pizzahawaiii** [comment]
Never mind, I see you added the Chinese translations to your fork and I just took them from there.

**Comment by Qeynos** [comment]
> Never mind, I see you added the Mandarin translations to your fork and I just took them from there.

i took them from addon WorldBuffsTracker in chinese community, it matched the yell npc's name
`WBT_Options.NPC = {
    Onyxia_Alliance = {name="玛丁雷少校", yell="一起庆祝英雄的诞生"},
    Nefarian_Alliance = {name="艾法希比元帅", yell="黑石领主已经被干掉了"},
    Onyxia_Horde = {name="伦萨克", yell="奥妮克希亚已经被斩杀了"},
    Nefarian_Horde = {name="萨鲁法尔大王", yell="奈法利安被杀掉了"},
}`
